# Generated by Django 4.2.15 on 2024-12-18 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_articletags_alter_article_category_article_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('budget', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='adv',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adv', to='blog.adv'),
        ),
    ]
