# Generated by Django 4.2.15 on 2024-12-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_adv_article_adv'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv',
            name='count_of_sale',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
